"""add_on_hold_ticket_state

Revision ID: 192f9e4532bd
Revises: f83781d4306d
Create Date: 2025-03-29 01:23:54.246634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer


# revision identifiers, used by Alembic.
revision = '192f9e4532bd'
down_revision = 'f83781d4306d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tickets', 'ticket_priorities', ['priority'], ['id'])
    
    # Add 'on hold' to ticket_states table
    ticket_states = table('ticket_states',
        column('id', Integer),
        column('name', String)
    )
    
    op.bulk_insert(
        ticket_states,
        [
            {'name': 'on hold'}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    
    # Remove 'on hold' from ticket_states table
    ticket_states = table('ticket_states',
        column('id', Integer),
        column('name', String)
    )
    
    op.execute(
        ticket_states.delete().where(ticket_states.c.name == 'on hold')
    )
    # ### end Alembic commands ### 