"""Add priority field to tickets

Revision ID: 54152bc9890f
Revises: 6df69d3c3dfe
Create Date: 2025-03-23 16:37:08.311069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54152bc9890f'
down_revision = '6df69d3c3dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('tickets', sa.Column('priority', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'ticket_priorities', ['priority'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'priority')
    op.drop_table('ticket_priorities')
    # ### end Alembic commands ### 