"""add_test_steps_to_ticket

Revision ID: 6df69d3c3dfe
Revises: 20240323_create_comments
Create Date: 2025-03-23 15:35:12.777717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df69d3c3dfe'
down_revision = '20240323_create_comments'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('test_steps', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'test_steps')
    # ### end Alembic commands ### 